# -*- coding: utf-8 -*-
"""RAFT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BS72TEyTanXDx4g0MjPAxRSvcnugrued
"""

# Cell 1: Install Unsloth and optimizations
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps xformers trl peft accelerate bitsandbytes

# Cell 2: Unsloth Qwen 2.5 Fine-Tuning Script
import json
import torch
from datasets import Dataset
from unsloth import FastLanguageModel
from unsloth.chat_templates import get_chat_template
from trl import SFTTrainer
from transformers import TrainingArguments

# ==========================================
# 1. Configuration
# ==========================================
MODEL_NAME = "unsloth/Qwen2.5-3B-Instruct"
DATA_PATH = "/content/raft_training_data.jsonl"
OUTPUT_DIR = "./graft-qwen-adapters"
MAX_SEQ_LENGTH = 2048

print("1. Loading Unsloth Model (Optimized for T4)...")
# Unsloth automatically handles the dtype safely for T4 GPUs
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = MODEL_NAME,
    max_seq_length = MAX_SEQ_LENGTH,
    dtype = None, # Auto-detects float16 for T4
    load_in_4bit = True,
)

# Apply standard ChatML formatting automatically
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "chatml",
)

# ==========================================
# 2. Data Preparation
# ==========================================
print("2. Formatting RAFT Dataset...")
raw_data = []
with open(DATA_PATH, "r", encoding="utf-8") as f:
    for line in f:
        raw_data.append(json.loads(line))

def format_chat(example):
    # Convert your RAFT data into standard OpenAI/ChatML conversation format
    conversation = [
        {"role": "system", "content": "You are an expert algorithmic assistant. Use the provided context to answer the question."},
        {"role": "user", "content": f"Context:\n{example['context']}\n\nQuestion:\n{example['question']}"},
        {"role": "assistant", "content": example['answer']}
    ]
    # Apply the tokenizer's chat template
    text = tokenizer.apply_chat_template(conversation, tokenize=False, add_generation_prompt=False)
    return {"text": text}

dataset = Dataset.from_list(raw_data)
dataset = dataset.map(format_chat)

# ==========================================
# 3. Setup LoRA with Unsloth Kernels
# ==========================================
print("3. Attaching LoRA Adapters...")
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 32,
    lora_dropout = 0, # Unsloth requires dropout=0 for speed optimizations
    bias = "none",
    use_gradient_checkpointing = "unsloth", # Saves massive amounts of VRAM
    random_state = 3407,
)

# ==========================================
# 4. Training
# ==========================================
print("4. Initializing Trainer...")
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = MAX_SEQ_LENGTH,
    dataset_num_proc = 2,
    packing = False, # Can set to True to train 5x faster if sequences are short
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 60, # Increase this to ~200-300 for a full run
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(), # MAGIC FIX: Dynamically protects your T4
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = OUTPUT_DIR,
        report_to = "none",
    ),
)

print("Starting Training! 🚀")
trainer.train()

# ==========================================
# 5. Save the Adapters
# ==========================================
print("Saving fine-tuned adapters...")
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print("✅ Training Complete and Adapters Saved!")

# Cell 3: Test the Fine-Tuned Model
print("Running Inference Test...")
# Unsloth switches the model into super-fast generation mode
FastLanguageModel.for_inference(model)

# Make up a mock algorithmic question based on your dataset
test_context = "Segment trees are used to answer range queries and update elements in logarithmic time."
test_question = "What is the primary use of a segment tree?"

messages = [
    {"role": "system", "content": "You are an expert algorithmic assistant. Use the provided context to answer the question."},
    {"role": "user", "content": f"Context:\n{test_context}\n\nQuestion:\n{test_question}"},
]

# Format and generate
inputs = tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True, # Tells the model to start speaking
    return_tensors = "pt",
).to("cuda")

# Generate the answer
from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer, skip_prompt=True)
print("\n--- GRAFT Model Response ---")
_ = model.generate(input_ids = inputs, streamer = text_streamer, max_new_tokens = 150, use_cache = True)

